# More on linear algebra
## Instructions:
* Go through the notebook and complete the tasks. 
* Make sure you understand the examples given. If you need help, refer to the Essential readings or the documentation link provided, or go to the Topic 2 discussion forum. 
* When a question allows a free-form answer (e.g. what do you observe?), create a new markdown cell below and answer the question in the notebook. 
* Save your notebooks when you are done.
 
**Task 1:**
Go through the tutorial on Linear Algebra in Python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.
Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.


In [1]:
import numpy as np

#Code here - use code samples from link above

**Task 2:**
Create the following matrices:

$X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$ 

Then do the following:
1.	Multiply ```X``` with ```Y``` (```Z1=X*Y=XY```) and print the result. What do you observe? 
2.	Multiply ```X``` with ```Y``` transpose (```Z2=X*Y.T```) and print the result. What do you observe? 
3.	What can you tell about matrix ```Y```, given ```Z1``` and ```Z2```? 

In [58]:
x = np.array([
    [2, 3, 4],
    [1, 2, 3],

])

y = np.array([
    [0,1],
    [0,0],
    [1,0]
])

# this takes the last value, then the first value
print(np.dot(x, y))

y = np.array([
    [0],
    [1],
    [0]
])
print('only middle value')
print(np.dot(x, y))


[[4 2]
 [3 1]]
only middle value
[[3]
 [2]]


In [29]:
x = np.array([
    [2, 3, 4],
    [1, 2, 3],

])

y = np.array([
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

In [30]:
# 2.1
z1 = np.dot(x, y)
print(z1)

[[3 2 4]
 [2 1 3]]


In [24]:
y.T

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [21]:
z2 = np.dot(x, y.T)
print(z2)

[[3 2 4]
 [2 1 3]]


**Task 3:** 
Create a 2x2 identity matrix ```I``` using the NumPy function ```eye(dim)``` $$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$


In [42]:
#Code here
i = np.eye(2)
print(i)

[[1. 0.]
 [0. 1.]]


**Task 4:** 
1. Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2. Print the output.
3. What do you observe? 



In [45]:
x=np.array([2,3])
print(x)
#Code here

[2 3]


In [46]:
print(np.dot(i, x))

[2. 3.]


**Task 5:**
1.	Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2.	Print the output.
3.	What do you observe? 


In [49]:
x=np.array([[2,3],[4,5]])
print(x)
#Code here

[[2 3]
 [4 5]]


In [50]:
print(np.dot(i, x))

[[2. 3.]
 [4. 5.]]


**Task 6:**
1. Multiply (using dot) matrix $X$ with the inverse matrix, $X^{-1}$ (use the NumPy function ```linalg.inv``` to do so): $XX^{-1}$
2. What do you observe? 




In [60]:
x=np.array([[1,2],[0,1]])
#Code here
print(x)

[[1 2]
 [0 1]]


In [62]:
x_i = np.linalg.inv(x)
print(x_i)

[[ 1. -2.]
 [ 0.  1.]]


In [64]:
print(np.dot(x, x_i))

[[1. 0.]
 [0. 1.]]
